[package]
name = "varseq"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0.17"
async-graphql-axum = "7.0.17"
axum = "0.8.7"
rayon = "1.11.0"
sqlx = { version = "0.8.6", features = ["postgres"] }
terra = "0.2.0"
tokio = { version = "1.48.0", features = ["full"] }
